// <auto-generated />
using System;
using BlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241229100932_podcasts")]
    partial class podcasts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorServer.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BlazorServer.Data.Podcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Podcasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Podcast 1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Podcast 2"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Podcast 3"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Podcast 4"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Podcast 5"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Podcast 6"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Podcast 7"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Podcast 8"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Podcast 9"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Podcast 10"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Podcast 11"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Podcast 12"
                        },
                        new
                        {
                            Id = 13,
                            Title = "Podcast 13"
                        },
                        new
                        {
                            Id = 14,
                            Title = "Podcast 14"
                        },
                        new
                        {
                            Id = 15,
                            Title = "Podcast 15"
                        },
                        new
                        {
                            Id = 16,
                            Title = "Podcast 16"
                        },
                        new
                        {
                            Id = 17,
                            Title = "Podcast 17"
                        },
                        new
                        {
                            Id = 18,
                            Title = "Podcast 18"
                        },
                        new
                        {
                            Id = 19,
                            Title = "Podcast 19"
                        },
                        new
                        {
                            Id = 20,
                            Title = "Podcast 20"
                        },
                        new
                        {
                            Id = 21,
                            Title = "Podcast 21"
                        },
                        new
                        {
                            Id = 22,
                            Title = "Podcast 22"
                        },
                        new
                        {
                            Id = 23,
                            Title = "Podcast 23"
                        },
                        new
                        {
                            Id = 24,
                            Title = "Podcast 24"
                        },
                        new
                        {
                            Id = 25,
                            Title = "Podcast 25"
                        },
                        new
                        {
                            Id = 26,
                            Title = "Podcast 26"
                        },
                        new
                        {
                            Id = 27,
                            Title = "Podcast 27"
                        },
                        new
                        {
                            Id = 28,
                            Title = "Podcast 28"
                        },
                        new
                        {
                            Id = 29,
                            Title = "Podcast 29"
                        },
                        new
                        {
                            Id = 30,
                            Title = "Podcast 30"
                        },
                        new
                        {
                            Id = 31,
                            Title = "Podcast 31"
                        },
                        new
                        {
                            Id = 32,
                            Title = "Podcast 32"
                        },
                        new
                        {
                            Id = 33,
                            Title = "Podcast 33"
                        },
                        new
                        {
                            Id = 34,
                            Title = "Podcast 34"
                        },
                        new
                        {
                            Id = 35,
                            Title = "Podcast 35"
                        },
                        new
                        {
                            Id = 36,
                            Title = "Podcast 36"
                        },
                        new
                        {
                            Id = 37,
                            Title = "Podcast 37"
                        },
                        new
                        {
                            Id = 38,
                            Title = "Podcast 38"
                        },
                        new
                        {
                            Id = 39,
                            Title = "Podcast 39"
                        },
                        new
                        {
                            Id = 40,
                            Title = "Podcast 40"
                        },
                        new
                        {
                            Id = 41,
                            Title = "Podcast 41"
                        },
                        new
                        {
                            Id = 42,
                            Title = "Podcast 42"
                        },
                        new
                        {
                            Id = 43,
                            Title = "Podcast 43"
                        },
                        new
                        {
                            Id = 44,
                            Title = "Podcast 44"
                        },
                        new
                        {
                            Id = 45,
                            Title = "Podcast 45"
                        },
                        new
                        {
                            Id = 46,
                            Title = "Podcast 46"
                        },
                        new
                        {
                            Id = 47,
                            Title = "Podcast 47"
                        },
                        new
                        {
                            Id = 48,
                            Title = "Podcast 48"
                        },
                        new
                        {
                            Id = 49,
                            Title = "Podcast 49"
                        },
                        new
                        {
                            Id = 50,
                            Title = "Podcast 50"
                        },
                        new
                        {
                            Id = 51,
                            Title = "Podcast 51"
                        },
                        new
                        {
                            Id = 52,
                            Title = "Podcast 52"
                        },
                        new
                        {
                            Id = 53,
                            Title = "Podcast 53"
                        },
                        new
                        {
                            Id = 54,
                            Title = "Podcast 54"
                        },
                        new
                        {
                            Id = 55,
                            Title = "Podcast 55"
                        },
                        new
                        {
                            Id = 56,
                            Title = "Podcast 56"
                        },
                        new
                        {
                            Id = 57,
                            Title = "Podcast 57"
                        },
                        new
                        {
                            Id = 58,
                            Title = "Podcast 58"
                        },
                        new
                        {
                            Id = 59,
                            Title = "Podcast 59"
                        },
                        new
                        {
                            Id = 60,
                            Title = "Podcast 60"
                        },
                        new
                        {
                            Id = 61,
                            Title = "Podcast 61"
                        },
                        new
                        {
                            Id = 62,
                            Title = "Podcast 62"
                        },
                        new
                        {
                            Id = 63,
                            Title = "Podcast 63"
                        },
                        new
                        {
                            Id = 64,
                            Title = "Podcast 64"
                        },
                        new
                        {
                            Id = 65,
                            Title = "Podcast 65"
                        },
                        new
                        {
                            Id = 66,
                            Title = "Podcast 66"
                        },
                        new
                        {
                            Id = 67,
                            Title = "Podcast 67"
                        },
                        new
                        {
                            Id = 68,
                            Title = "Podcast 68"
                        },
                        new
                        {
                            Id = 69,
                            Title = "Podcast 69"
                        },
                        new
                        {
                            Id = 70,
                            Title = "Podcast 70"
                        },
                        new
                        {
                            Id = 71,
                            Title = "Podcast 71"
                        },
                        new
                        {
                            Id = 72,
                            Title = "Podcast 72"
                        },
                        new
                        {
                            Id = 73,
                            Title = "Podcast 73"
                        },
                        new
                        {
                            Id = 74,
                            Title = "Podcast 74"
                        },
                        new
                        {
                            Id = 75,
                            Title = "Podcast 75"
                        },
                        new
                        {
                            Id = 76,
                            Title = "Podcast 76"
                        },
                        new
                        {
                            Id = 77,
                            Title = "Podcast 77"
                        },
                        new
                        {
                            Id = 78,
                            Title = "Podcast 78"
                        },
                        new
                        {
                            Id = 79,
                            Title = "Podcast 79"
                        },
                        new
                        {
                            Id = 80,
                            Title = "Podcast 80"
                        },
                        new
                        {
                            Id = 81,
                            Title = "Podcast 81"
                        },
                        new
                        {
                            Id = 82,
                            Title = "Podcast 82"
                        },
                        new
                        {
                            Id = 83,
                            Title = "Podcast 83"
                        },
                        new
                        {
                            Id = 84,
                            Title = "Podcast 84"
                        },
                        new
                        {
                            Id = 85,
                            Title = "Podcast 85"
                        },
                        new
                        {
                            Id = 86,
                            Title = "Podcast 86"
                        },
                        new
                        {
                            Id = 87,
                            Title = "Podcast 87"
                        },
                        new
                        {
                            Id = 88,
                            Title = "Podcast 88"
                        },
                        new
                        {
                            Id = 89,
                            Title = "Podcast 89"
                        },
                        new
                        {
                            Id = 90,
                            Title = "Podcast 90"
                        },
                        new
                        {
                            Id = 91,
                            Title = "Podcast 91"
                        },
                        new
                        {
                            Id = 92,
                            Title = "Podcast 92"
                        },
                        new
                        {
                            Id = 93,
                            Title = "Podcast 93"
                        },
                        new
                        {
                            Id = 94,
                            Title = "Podcast 94"
                        },
                        new
                        {
                            Id = 95,
                            Title = "Podcast 95"
                        },
                        new
                        {
                            Id = 96,
                            Title = "Podcast 96"
                        },
                        new
                        {
                            Id = 97,
                            Title = "Podcast 97"
                        },
                        new
                        {
                            Id = 98,
                            Title = "Podcast 98"
                        },
                        new
                        {
                            Id = 99,
                            Title = "Podcast 99"
                        },
                        new
                        {
                            Id = 100,
                            Title = "Podcast 100"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
